name: Build Docs PDF

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container: pandoc/latex:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF with Pandoc
        run: |
          mkdir -p build
          pandoc docs/Documentation-Full.md -o build/Documentation-Full.pdf \
            --from gfm --toc --number-sections \
            -V geometry:margin=1in \
            -V mainfont="DejaVu Serif" -V monofont="DejaVu Sans Mono"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: build/Documentation-Full.pdf
